# Template registry
# Maps template paths to names and reload commands

[templates]
# name = { path = "relative/to/dotfiles", reload = "command" }
mako = { path = "tools/mako/config.tera", reload = "makoctl reload" }
btop = { path = "tools/btop/catppuccin_mocha.theme.tera" }
eza = { path = "tools/eza/catppuccin.yml.tera" }
wlogout = { path = "arch/wlogout/blue.css.tera", link = "/arch/wlogout" }
hyprbars = { path = "arch/hyprbars/hyprbars.conf.tera", reload = "hyprctl reload" }
swappy = { path = "arch/swappy/config.tera" }
bat = { path = "tools/bat/config.tera" }
hyprland = { path = "arch/hyprland/hyprland.conf.tera", reload = "hyprctl reload" }
hyprtoolkit = { path = "arch/hyprland/hyprtoolkit.conf.tera", reload = "hyprctl reload" }
hyprlock-palette = { path = "arch/hyprlock/mocha.conf.tera" }
kitty = { path = "tools/kitty/kitty.conf.tera", reload = "pkill -USR1 kitty" }
waybar-style = { path = "tools/waybar/style.css.tera", reload = "systemctl --user restart waybar" }
waybar-config = { path = "tools/waybar/config.jsonc.tera", reload = "systemctl --user restart waybar" }
rofi = { path = "tools/rofi/catppuccin-mocha.rasi.tera" }
lazygit = { path = "tools/lazygit/config.yaml.tera" }
gitconfig = { path = "tools/git/gitconfig.tera" }
starship = { path = "tools/starship/starship.toml.tera" }
firefox-theme = { path = "arch/firefox/theme-url.txt.tera", reload = "firefox \"$(cat ~/.dotfiles/arch/firefox/theme-url.txt)\"" }
mouse-leds = { path = "arch/piper/set-leds.sh.tera", reload = "~/.dotfiles/arch/piper/set-leds.sh" }

# Qt
qt6ct-colors = { path = "lib/qt/qt6ct/style-colors.conf.tera" }
qt6ct-config = { path = "lib/qt/qt6ct/qt6ct.conf.tera" }

# GTK / NWG-Look
gtk3-settings = { path = "arch/nwg-look/settings.ini.tera" }
gtk4-settings = { path = "arch/nwg-look/gtk-4.0/settings.ini.tera" }
gtk2-settings = { path = "arch/nwg-look/gtkrc-2.0.tera" }
xsettingsd = { path = "arch/nwg-look/xsettingsd.conf.tera" }
gtk3-css = { path = "arch/nwg-look/gtk.css.tera" }
gtk4-css = { path = "arch/nwg-look/gtk-4.0/gtk.css.tera" }
libadwaita = { path = "arch/nwg-look/gtk-4.0/libadwaita.css.tera" }
libadwaita-tweaks = { path = "arch/nwg-look/gtk-4.0/libadwaita-tweaks.css.tera" }
gtk4-dark-css = { path = "arch/nwg-look/gtk-4.0/gtk-dark.css.tera" }
gtk4-bullet-svg = { path = "arch/nwg-look/gtk-4.0/assets/bullet-symbolic.svg.tera" }
gtk4-check-svg = { path = "arch/nwg-look/gtk-4.0/assets/check-symbolic.svg.tera" }
gtk4-dash-svg = { path = "arch/nwg-look/gtk-4.0/assets/dash-symbolic.svg.tera" }
gtk4-devel-svg = { path = "arch/nwg-look/gtk-4.0/assets/devel-symbolic.svg.tera" }

# KDE / Dolphin
kdeglobals = { path = "arch/dolphin/kdeglobals.tera" }
kde-colorscheme = { path = "arch/dolphin/catppuccin-mocha.colors.tera", link = "/arch/dolphin" }
dolphinrc = { path = "arch/dolphin/dolphinrc.tera", link = "/arch/dolphin" }

# SDDM
sddm-theme = { path = "tools/sddm/theme.conf.tera" }

# Icons
papirus-folders = { path = "tools/papirus/set-folders.sh.tera", reload = "~/.dotfiles/tools/papirus/set-folders.sh" }

# Editors
vscode = { path = "editors/vscode/settings.json.tera" }
