[pyprland]
plugins = ["magnify", "scratchpads"]

[magnify]
factor = 2
duration = 15

[scratchpads.btop]
animation = "fromTop"
command = "kitty --class btop-scratch btop"
class = "btop-scratch"
lazy = true

[scratchpads.pavucontrol]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "25% 60%"
position = "74% 5%"
unfocus = "hide"
lazy = true

[scratchpads.helvum]
animation = "fromRight"
command = "helvum"
class = "org.pipewire.Helvum"
size = "50% 60%"
position = "49% 5%"
unfocus = "hide"
lazy = true
