[pyprland]
plugins = ["magnify", "scratchpads"]
include = ["~/.config/pypr/conf.d/"]

[magnify]
factor = 2
duration = 15

[scratchpads.font]
animation = "fromTop"
command = "sh -c 'kitty --class cfg-font-preview -o \"font_family=$(cat /tmp/cfg-font-preview)\" cfg font --scratchpad'"
class = "cfg-font-preview"
unfocus = "hide"
lazy = false
