# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
palette = "catppuccin_mocha"

# Pure preset
format = """
$shell\
$sudo\
$directory\
$git_branch\
$git_metrics\
$git_state\
$cmd_duration\
$line_break\
$character"""

right_format = """
$bun\
$c\
$cpp\
$cmake\
$conda\
$deno\
$dotnet\
$docker_context\
$elixir\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$python\
$perl\
$php\
$rlang\
$ruby\
$rust\
$swift\
$memory_usage\
$time"""

[shell]
zsh_indicator = 'îœ’ '
powershell_indicator = 'îœ '
style = 'cyan bold'
disabled = false

[sudo]
format = '[$symbol]($style)'
symbol = "ó±€Š  "
disabled = false

[directory]
read_only = " ó°Œ¾"
truncation_length = 4
style = "bold lavender"

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](sapphire)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "red"

[git_branch]
symbol = "ï˜ "
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold mauve"

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = true

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[memory_usage]
disabled = false
threshold = 75                                   # only show if memory usage is above this percentage
symbol = 'ó°› '
format = '$symbol [${ram}( | ${swap})]($style) '
style = 'bold dimmed red'

[time]
disabled = false
format = "[ $time]($style)"
utc_time_offset = "local"
style = "italic dimmed white"

[bun]
symbol = "î¯ "
format = "[$symbol bun $version ]($style)"
style = "bright-black"

[c]
symbol = "î˜ "
format = "[$symbol c $version(-$name) ]($style)"
style = "bright-black"

[cpp]
symbol = "î˜ "
format = "[$symbol cpp $version(-$name) ]($style)"
style = "bright-black"

[cmake]
symbol = "î” "
format = "[$symbol cmake $version ]($style)"
style = "bright-black"

[conda]
symbol = "ï„Œ "
format = "[$symbol conda $version ]($style)"
style = "bright-black"

[deno]
symbol = "îŸ€ "
format = "[$symbol deno $version ]($style)"
style = "bright-black"

[dotnet]
symbol = "î¿"
format = "[$symbol deno $version (ğŸ¯ $tfm )]($style)"
style = "bright-black"

[docker_context]
symbol = "ïŒˆ "
format = "[$symbol docker $version ]($style)"
style = "bright-black"

[elixir]
symbol = "î˜­ "
format = "[$symbol elixir $version (OTP $otp_version )]($style)"
style = "bright-black"

[golang]
symbol = "î˜§ "
format = "[$symbol go $version ]($style)"
style = "bright-black"

[haskell]
symbol = "î· "
format = "[$symbol haskell $version ]($style)"
style = "bright-black"

[java]
symbol = "î‰– "
format = "[$symbol java $version ]($style)"
style = "bright-black"

[julia]
symbol = "î˜¤ "
format = "[$symbol julia $version ]($style)"
style = "bright-black"

[lua]
symbol = "î˜  "
format = "[$symbol lua $version ]($style)"
style = "bright-black"

[nodejs]
symbol = "îœ˜ "
format = "[$symbol node $version ]($style)"
style = "bright-black"

[perl]
symbol = "î™¾ "
format = "[$symbol perl $version ]($style)"
style = "bright-black"

[php]
symbol = "î˜ˆ "
format = "[$symbol php $version ]($style)"
style = "bright-black"

[rlang]
symbol = "ó°Ÿ” "
format = "[$symbol R $version ]($style)"
style = "bright-black"

[ruby]
symbol = "î‘ "
format = "[$symbol ruby $version ]($style)"
style = "bright-black"

[rust]
symbol = "ó±˜— "
format = "[$symbol rust $version ]($style)"
style = "bright-black"

[swift]
symbol = "î• "
format = "[$symbol swift $version ]($style)"
style = "bright-black"

[python]
symbol = "îˆµ "
format = "($virtualenv) [$symbol python $pyenv_prefix($version )]($style)"
style = "bright-black"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
