os:
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-tab {{filename}})'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-tab {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>")'
  # Whether lazygit suspends until an edit process returns
  editInTerminal: true
# Use Git Delta for diffs
git:
  pagers:
    - colorArg: always
      pager: delta --features lazygit
# Use neovim for writing commit messages by default
keybinding:
  files:
    commitChanges: C # using the interactive commit dialog
    commitChangesWithEditor: c # using neovim
  commits:
    openLogMenu: <c-g>
    renameCommit: R
    renameCommitWithEditor: r
# Do not prompt after git commands
promptToReturnFromSubprocess: false
notARepository: "quit"
gui:
  # UI
  showRandomTip: false
  disableStartupPopups: true
  showBottomLine: true
  showCommandLog: false
  nerdFontsVersion: "3"
  showFileIcons: true
  border: single
  skipRewordInEditorWarning: true
  skipAmendWarning: true
  # Theme (Catppuccin Mocha)
  theme:
    activeBorderColor:
      - "#f38ba8"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#f38ba8"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f38ba8"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
  authorColors:
    "*": "#b4befe"
customCommands:
  - key: D
    description: "Visual diff (kitten diff)"
    command: "git difftool --no-symlinks -y -- {{.SelectedFile.Name}}"
    context: files
    output: terminal
